export const travelLocations = [
    {
        weatherTags: ["sunny"],
        isGif: false,
        image: "./images/angry.jpeg",
        alt: "A cat looking sunny",
    },
    {
        weatherTags: ["cloudy", "wet"],
        isGif: false,
        image: "./images/angry2.jpeg",
        alt: "A cat looking sunny",
    },
    {
        weatherTags: ["sunny"],
        isGif: false,
        image: "./images/angry3.jpeg",
        alt: "A cat looking sunny",
    },
    {
        weatherTags: ["snow", "cold"],
        isGif: false,
        image: "./images/confused.jpeg",
        alt: "A cat looking confused",
    },
    {
        weatherTags: ["jungle", "tropic"],
        isGif: false,
        image: "./images/dominant.jpeg",
        alt: "A cat looking dominant",
    },
    {
        weatherTags: ["desert", "dry"],
        isGif: false,
        image: "./images/happy.jpeg",
        alt: "A cat looking happy",
    },
    {
        weatherTags: ["urban"],
        isGif: false,
        image: "./images/urban.jpeg",
        alt: "A cat looking urban",
    },
    {
        weatherTags: ["urban"],
        isGif: false,
        image: "./images/urban1.jpeg",
        alt: "A cat looking urban",
    },
    {
        weatherTags: ["urban"],
        isGif: false,
        image: "./images/insomnia.jpeg",
        alt: "A cat looking insomniac",
    },
    {
        weatherTags: ["urban"],
        isGif: false,
        image: "./images/insomnia1.jpeg",
        alt: "A cat looking insomniac",
    },
    {
        weatherTags: ["relaxed"],
        isGif: false,
        image: "./images/lazy.jpeg",
        alt: "A cat looking lazy",
    },
    {
        weatherTags: ["scared"],
        isGif: false,
        image: "./images/nervous.jpeg",
        alt: "A cat looking nervous",
    },
    {
        weatherTags: ["desert"],
        isGif: false,
        image: "./images/sad.jpeg",
        alt: "A cat looking sad",
    },
    {
        weatherTags: ["desert", "sunny"],
        isGif: false,
        image: "./images/sad1.jpeg",
        alt: "A cat looking sad",
    },
    {
        weatherTags: ["sunny"],
        isGif: true,
        image: "./images/angry.gif",
        alt: "A cat looking sunny",
    },
    {
        weatherTags: ["sunny"],
        isGif: true,
        image: "./images/angry2.gif",
        alt: "A cat looking angry",
    },
    {
        weatherTags: ["crowded"],
        isGif: true,
        image: "./images/confused2.gif",
        alt: "A cat looking confused",
    },
    {
        weatherTags: ["dominant"],
        isGif: true,
        image: "./images/dominant.gif",
        alt: "A cat looking dominant",
    },
    {
        weatherTags: ["jungle"],
        isGif: true,
        image: "./images/happy.gif",
        alt: "A cat looking happy",
    },
    {
        weatherTags: ["urban", "warm", "crowded"],
        isGif: true,
        image: "./images/confused.gif",
        alt: "A cat looking urban",
    },
    {
        weatherTags: ["urban"],
        isGif: true,
        image: "./images/urban.gif",
        alt: "A cat looking urban",
    },
    {
        weatherTags: ["urban"],
        isGif: true,
        image: "./images/urban2.gif",
        alt: "A cat looking urban",
    },
    {
        weatherTags: ["urban", "rainy"],
        isGif: true,
        image: "./images/insomnia2.gif",
        alt: "A cat looking insomniac",
    },
]